version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3333:3000"
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - faucet-network
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "29000:29000"  # Expose backend port to host
    environment:
      - PORT=29000
      - RPC_URL=http://host.docker.internal:32002
      - PRIVATE_KEY=${PRIVATE_KEY}
      - HCAPTCHA_SECRET_KEY=${HCAPTCHA_SECRET_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - faucet-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  faucet-network:
    driver: bridge